# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: buildFilialfinder

on:
  push:
    branches: [ master ]
 # pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm i
        npm run init:app  
        npm run build --if-present
  #  - run: npm test
   
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true
          
     # Runs a set of commands using the runners shell
    - name: ftp-action
    # You may pin to the exact commit or the version.
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
          # FTP host
          ftp-server: sftp://login-12.hoststar.at:5544/projects/filialfinder/
          # FTP user
          ftp-username: 'githubaction.gisolutions.at'
          # FTP password
          ftp-password: 'Testpasswort01!'
          git-ftp-args: --insecure
          local-dir: dist
